// packages/vue/src/components/dialogs/InsertImageDialog.vue
<template>
  <div v-if="isOpen" class="dialog-overlay" @mousedown.self="close">
    <div class="dialog" @mousedown.stop @keydown.stop>
      <div class="dialog__header">
        <span class="dialog__title">{{ t('dialogs.insertImage.title') }}</span>
        <button class="dialog__close" :aria-label="t('common.closeDialog')" @click="close">
          ✕
        </button>
      </div>
      <div class="dialog__body">
        <!-- Drop zone / file input -->
        <div
          class="drop-zone"
          :class="{ 'drop-zone--active': isDragOver }"
          @dragover.prevent="isDragOver = true"
          @dragleave="isDragOver = false"
          @drop.prevent="handleDrop"
          @click="fileInput?.click()"
        >
          <template v-if="!preview">
            <div class="drop-zone__icon">
              <MaterialSymbol name="image" :size="48" />
            </div>
            <div class="drop-zone__text">{{ t('dialogs.insertImage.uploadText') }}</div>
            <div class="drop-zone__hint">{{ t('dialogs.insertImage.uploadSubtext') }}</div>
          </template>
          <img
            v-else
            :src="preview"
            class="drop-zone__preview"
            :alt="t('dialogs.insertImage.preview')"
          />
        </div>
        <input
          ref="fileInput"
          type="file"
          accept="image/*"
          style="display: none"
          :aria-label="t('dialogs.insertImage.uploadAriaLabel')"
          @change="handleFileChange"
        />

        <div v-if="error" class="drop-zone__error">{{ error }}</div>

        <!-- Dimensions -->
        <div v-if="preview" class="image-controls">
          <label
            >{{ t('dialogs.insertImage.widthLabel') }}
            <input
              v-model.number="imgWidth"
              type="number"
              min="1"
              max="2000"
              class="dim-input"
              @input="onWidthChange"
          /></label>
          <label
            >{{ t('dialogs.insertImage.heightLabel') }}
            <input
              v-model.number="imgHeight"
              type="number"
              min="1"
              max="2000"
              class="dim-input"
              @input="onHeightChange"
          /></label>
          <label class="lock-label"
            ><input type="checkbox" v-model="lockAspect" />
            {{
              lockAspect
                ? t('dialogs.insertImage.aspectRatioLocked')
                : t('dialogs.insertImage.aspectRatioUnlocked')
            }}</label
          >
        </div>

        <!-- Alt text -->
        <div v-if="preview" class="image-controls">
          <label style="flex: 1"
            >{{ t('dialogs.insertImage.altTextLabel') }}
            <input
              v-model="altText"
              class="alt-input"
              :placeholder="t('dialogs.insertImage.altTextPlaceholder')"
          /></label>
        </div>

        <!-- Actions -->
        <div v-if="preview" class="dialog__actions">
          <button class="dialog__btn" @click="reset">{{ t('common.clear') }}</button>
          <button class="dialog__btn dialog__btn--primary" @mousedown.prevent="insertImage">
            {{ t('dialogs.insertImage.insertButton') }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useTranslation } from '../../i18n';
import MaterialSymbol from '../ui/MaterialSymbol.vue';

const { t } = useTranslation();

defineProps<{ isOpen: boolean }>();
const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'insert', data: { src: string; width: number; height: number; alt: string }): void;
}>();

const fileInput = ref<HTMLInputElement | null>(null);
const preview = ref('');
const imgWidth = ref(400);
const imgHeight = ref(300);
const lockAspect = ref(true);
const altText = ref('');
const error = ref('');
const isDragOver = ref(false);
let aspectRatio = 1;

function close() {
  emit('close');
}

function reset() {
  preview.value = '';
  error.value = '';
  altText.value = '';
  imgWidth.value = 400;
  imgHeight.value = 300;
}

function handleDrop(e: DragEvent) {
  isDragOver.value = false;
  const file = e.dataTransfer?.files?.[0];
  if (file) loadFile(file);
}

function handleFileChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (file) loadFile(file);
}

function loadFile(file: File) {
  error.value = '';
  if (!file.type.startsWith('image/')) {
    error.value = t('dialogs.insertImage.invalidFile');
    return;
  }
  if (file.size > 10 * 1024 * 1024) {
    error.value = t('dialogs.insertImage.fileTooLarge');
    return;
  }

  altText.value = file.name.replace(/\.[^.]+$/, '');
  const reader = new FileReader();
  reader.onload = () => {
    const dataUrl = reader.result as string;
    const img = new Image();
    img.onload = () => {
      let w = img.naturalWidth;
      let h = img.naturalHeight;
      // Constrain to max 800x600
      if (w > 800) {
        h = Math.round(h * (800 / w));
        w = 800;
      }
      if (h > 600) {
        w = Math.round(w * (600 / h));
        h = 600;
      }
      imgWidth.value = w;
      imgHeight.value = h;
      aspectRatio = w / h;
      preview.value = dataUrl;
    };
    img.onerror = () => {
      error.value = t('dialogs.insertImage.loadFailed');
    };
    img.src = dataUrl;
  };
  reader.onerror = () => {
    error.value = t('dialogs.insertImage.readFailed');
  };
  reader.readAsDataURL(file);
}

function onWidthChange() {
  if (lockAspect.value && aspectRatio) {
    imgHeight.value = Math.round(imgWidth.value / aspectRatio);
  }
}

function onHeightChange() {
  if (lockAspect.value && aspectRatio) {
    imgWidth.value = Math.round(imgHeight.value * aspectRatio);
  }
}

function insertImage() {
  if (!preview.value) return;
  emit('insert', {
    src: preview.value,
    width: imgWidth.value,
    height: imgHeight.value,
    alt: altText.value,
  });
  reset();
  close();
}
</script>

<style scoped>
.dialog-overlay {
  position: fixed;
  inset: 0;
  background: var(--doc-overlay);
  z-index: 300;
  display: flex;
  align-items: center;
  justify-content: center;
}
.dialog {
  background: var(--doc-surface);
  border-radius: 8px;
  box-shadow: 0 8px 30px var(--doc-shadow);
  min-width: 400px;
  max-width: 90vw;
}
.dialog__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border-bottom: 1px solid var(--doc-border);
}
.dialog__title {
  font-weight: 600;
  font-size: 14px;
  color: var(--doc-text);
}
.dialog__close {
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 14px;
  color: var(--doc-text-muted);
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 4px;
}
.dialog__close:hover {
  background: var(--doc-bg-hover);
}
.dialog__body {
  padding: 16px;
}
.dialog__actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 12px;
}
.dialog__btn {
  padding: 6px 16px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  cursor: pointer;
  font-size: 13px;
  background: var(--doc-surface);
}
.dialog__btn--primary {
  background: var(--doc-primary);
  color: var(--doc-on-primary);
  border-color: var(--doc-primary);
}
.dialog__btn--primary:hover {
  background: var(--doc-primary);
}

.drop-zone {
  border: 2px dashed var(--doc-border-dark);
  border-radius: 8px;
  padding: 24px;
  text-align: center;
  cursor: pointer;
  transition: border-color 0.2s;
  min-height: 120px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.drop-zone:hover,
.drop-zone--active {
  border-color: var(--doc-primary);
  background: var(--doc-primary-light);
}
.drop-zone__icon {
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--doc-text-subtle);
  margin-bottom: 8px;
}
.drop-zone__text {
  font-size: 13px;
  color: var(--doc-text-muted);
}
.drop-zone__hint {
  font-size: 11px;
  color: var(--doc-text-subtle);
  margin-top: 4px;
}
.drop-zone__preview {
  max-width: 100%;
  max-height: 200px;
  border-radius: 4px;
}
.drop-zone__error {
  color: var(--doc-error);
  font-size: 12px;
  margin-top: 8px;
}

.image-controls {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 12px;
  font-size: 13px;
}
.dim-input {
  width: 70px;
  padding: 4px 6px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  font-size: 13px;
}
.alt-input {
  width: 100%;
  padding: 4px 8px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  font-size: 13px;
  margin-top: 4px;
}
.lock-label {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  white-space: nowrap;
}
</style>

// packages/react/src/components/dialogs/InsertImageDialog.tsx
/**
 * Insert Image Dialog Component
 *
 * Modal dialog for inserting images into the document.
 * Supports file upload with preview and basic sizing options.
 *
 * Features:
 * - File input for image selection
 * - Drag and drop support
 * - Image preview
 * - Width/height controls with aspect ratio lock
 * - Alt text input
 */

import React, { useState, useCallback, useRef, useEffect } from 'react';
import type { CSSProperties, DragEvent, ChangeEvent } from 'react';
import { useTranslation } from '../../i18n';
import { MaterialSymbol } from '../ui/Icons';
import { useAspectLockedSize } from '../../hooks/useAspectLockedSize';

// ============================================================================
// TYPES
// ============================================================================

/**
 * Image data for insertion
 */
export interface ImageData {
  /** Base64 data URL or external URL */
  src: string;
  /** Image width in pixels */
  width: number;
  /** Image height in pixels */
  height: number;
  /** Alt text for accessibility */
  alt?: string;
  /** Original file name */
  fileName?: string;
  /** MIME type */
  mimeType?: string;
}

/**
 * Props for InsertImageDialog
 */
export interface InsertImageDialogProps {
  /** Whether the dialog is open */
  isOpen: boolean;
  /** Callback when dialog is closed */
  onClose: () => void;
  /** Callback when image is inserted */
  onInsert: (data: ImageData) => void;
  /** Maximum width in pixels (default: 800) */
  maxWidth?: number;
  /** Maximum height in pixels (default: 600) */
  maxHeight?: number;
  /** Accepted file types (default: image/*) */
  accept?: string;
  /** Additional CSS class */
  className?: string;
  /** Additional inline styles */
  style?: CSSProperties;
}

// ============================================================================
// STYLES
// ============================================================================

const DIALOG_OVERLAY_STYLE: CSSProperties = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'var(--doc-overlay)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 10000,
};

const DIALOG_CONTENT_STYLE: CSSProperties = {
  backgroundColor: 'var(--doc-surface)',
  borderRadius: '8px',
  boxShadow: '0 4px 20px var(--doc-shadow)',
  minWidth: '450px',
  maxWidth: '600px',
  width: '100%',
  margin: '20px',
  maxHeight: '90vh',
  overflow: 'auto',
};

const DIALOG_HEADER_STYLE: CSSProperties = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  padding: '16px 20px',
  borderBottom: '1px solid var(--doc-border)',
};

const DIALOG_TITLE_STYLE: CSSProperties = {
  margin: 0,
  fontSize: '18px',
  fontWeight: 600,
  color: 'var(--doc-text)',
};

const CLOSE_BUTTON_STYLE: CSSProperties = {
  background: 'none',
  border: 'none',
  fontSize: '20px',
  cursor: 'pointer',
  color: 'var(--doc-text-muted)',
  padding: '4px 8px',
  lineHeight: 1,
};

const DIALOG_BODY_STYLE: CSSProperties = {
  padding: '20px',
};

const DROP_ZONE_STYLE: CSSProperties = {
  border: '2px dashed var(--doc-border-input)',
  borderRadius: '8px',
  padding: '40px 20px',
  textAlign: 'center',
  cursor: 'pointer',
  transition: 'border-color 0.2s, background-color 0.2s',
  marginBottom: '16px',
};

const DROP_ZONE_ACTIVE_STYLE: CSSProperties = {
  ...DROP_ZONE_STYLE,
  borderColor: 'var(--doc-primary)',
  backgroundColor: 'var(--doc-primary-light)',
};

const DROP_ZONE_WITH_IMAGE_STYLE: CSSProperties = {
  ...DROP_ZONE_STYLE,
  padding: '20px',
  borderStyle: 'solid',
  borderColor: 'var(--doc-primary)',
};

const PREVIEW_CONTAINER_STYLE: CSSProperties = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  maxHeight: '250px',
  overflow: 'hidden',
};

const PREVIEW_IMAGE_STYLE: CSSProperties = {
  maxWidth: '100%',
  maxHeight: '250px',
  objectFit: 'contain',
  borderRadius: '4px',
};

const DROP_ZONE_ICON_STYLE: CSSProperties = {
  fontSize: '48px',
  color: 'var(--doc-text-placeholder)',
  marginBottom: '12px',
};

const DROP_ZONE_TEXT_STYLE: CSSProperties = {
  fontSize: '14px',
  color: 'var(--doc-text-muted)',
  marginBottom: '8px',
};

const DROP_ZONE_SUBTEXT_STYLE: CSSProperties = {
  fontSize: '12px',
  color: 'var(--doc-text-placeholder)',
};

const FORM_GROUP_STYLE: CSSProperties = {
  marginBottom: '16px',
};

const LABEL_STYLE: CSSProperties = {
  display: 'block',
  marginBottom: '6px',
  fontSize: '14px',
  fontWeight: 500,
  color: 'var(--doc-text)',
};

const INPUT_STYLE: CSSProperties = {
  width: '100%',
  padding: '10px 12px',
  border: '1px solid var(--doc-border-input)',
  borderRadius: '4px',
  fontSize: '14px',
  boxSizing: 'border-box',
};

const SIZE_ROW_STYLE: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '12px',
  marginBottom: '16px',
};

const SIZE_INPUT_STYLE: CSSProperties = {
  width: '100px',
  padding: '6px 8px',
  border: '1px solid var(--doc-border-input)',
  borderRadius: '4px',
  fontSize: '14px',
};

const INLINE_LABEL_STYLE: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: '6px',
  fontSize: '14px',
  color: 'var(--doc-text)',
  fontWeight: 500,
};

const LOCK_LABEL_STYLE: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: '6px',
  fontSize: '13px',
  color: 'var(--doc-text-muted)',
  cursor: 'pointer',
  whiteSpace: 'nowrap',
};

const DIALOG_FOOTER_STYLE: CSSProperties = {
  display: 'flex',
  justifyContent: 'flex-end',
  gap: '12px',
  padding: '16px 20px',
  borderTop: '1px solid var(--doc-border)',
};

const BUTTON_BASE_STYLE: CSSProperties = {
  padding: '10px 20px',
  borderRadius: '4px',
  fontSize: '14px',
  fontWeight: 500,
  cursor: 'pointer',
  border: 'none',
};

const PRIMARY_BUTTON_STYLE: CSSProperties = {
  ...BUTTON_BASE_STYLE,
  backgroundColor: 'var(--doc-primary)',
  color: 'var(--doc-on-primary)',
};

const SECONDARY_BUTTON_STYLE: CSSProperties = {
  ...BUTTON_BASE_STYLE,
  backgroundColor: 'var(--doc-bg-subtle)',
  color: 'var(--doc-text)',
  border: '1px solid var(--doc-border-input)',
};

const DISABLED_BUTTON_STYLE: CSSProperties = {
  ...BUTTON_BASE_STYLE,
  backgroundColor: 'var(--doc-border-input)',
  color: 'var(--doc-text-muted)',
  cursor: 'not-allowed',
};

// ============================================================================
// ICONS
// ============================================================================

function ImageIcon(): React.ReactElement {
  return (
    <span style={{ color: 'var(--doc-text-placeholder)' }}>
      <MaterialSymbol name="image" size={48} />
    </span>
  );
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

/**
 * InsertImageDialog - Modal for inserting images with preview and sizing
 */
export function InsertImageDialog({
  isOpen,
  onClose,
  onInsert,
  maxWidth = 800,
  maxHeight = 600,
  accept = 'image/*',
  className,
  style,
}: InsertImageDialogProps): React.ReactElement | null {
  const { t } = useTranslation();

  // State
  const [imageData, setImageData] = useState<ImageData | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const {
    width,
    height,
    lockAspect: aspectLocked,
    setLockAspect: setAspectLocked,
    handleWidthChange,
    handleHeightChange,
    seed: seedAspect,
  } = useAspectLockedSize();
  const [altText, setAltText] = useState('');
  const [error, setError] = useState<string | null>(null);

  // Refs
  const fileInputRef = useRef<HTMLInputElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);

  // Reset state when dialog opens/closes
  useEffect(() => {
    if (isOpen) {
      setImageData(null);
      setIsDragging(false);
      seedAspect(null, null);
      setAltText('');
      setError(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  /**
   * Process a file and load image data
   */
  const processFile = useCallback(
    (file: File) => {
      // Validate file type
      if (!file.type.startsWith('image/')) {
        setError(t('dialogs.insertImage.invalidFile'));
        return;
      }

      // Validate file size (max 10MB)
      if (file.size > 10 * 1024 * 1024) {
        setError(t('dialogs.insertImage.fileTooLarge'));
        return;
      }

      setError(null);

      const reader = new FileReader();
      reader.onload = (e) => {
        const src = e.target?.result as string;

        // Load image to get dimensions
        const img = new Image();
        img.onload = () => {
          let w = img.width;
          let h = img.height;

          // Scale down if exceeds max dimensions
          if (w > maxWidth || h > maxHeight) {
            const scaleW = maxWidth / w;
            const scaleH = maxHeight / h;
            const scale = Math.min(scaleW, scaleH);
            w = Math.round(w * scale);
            h = Math.round(h * scale);
          }

          seedAspect(w, h);
          setImageData({
            src,
            width: w,
            height: h,
            fileName: file.name,
            mimeType: file.type,
          });
        };
        img.src = src;
      };

      reader.onerror = () => {
        setError('Failed to read image file');
      };

      reader.readAsDataURL(file);
    },
    [maxWidth, maxHeight]
  );

  /**
   * Handle file input change
   */
  const handleFileChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) {
        processFile(file);
      }
    },
    [processFile]
  );

  /**
   * Handle drop zone click
   */
  const handleDropZoneClick = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  /**
   * Handle drag over
   */
  const handleDragOver = useCallback((e: DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  /**
   * Handle drag leave
   */
  const handleDragLeave = useCallback((e: DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  /**
   * Handle drop
   */
  const handleDrop = useCallback(
    (e: DragEvent) => {
      e.preventDefault();
      setIsDragging(false);

      const file = e.dataTransfer.files?.[0];
      if (file) {
        processFile(file);
      }
    },
    [processFile]
  );

  /**
   * Handle insert
   */
  const handleInsert = useCallback(() => {
    if (imageData && typeof width === 'number' && typeof height === 'number') {
      onInsert({
        ...imageData,
        width,
        height,
        alt: altText || undefined,
      });
    }
  }, [imageData, width, height, altText, onInsert]);

  /**
   * Handle keyboard events
   */
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      } else if (e.key === 'Enter' && imageData && !e.shiftKey) {
        e.preventDefault();
        handleInsert();
      }
    },
    [onClose, imageData, handleInsert]
  );

  /**
   * Handle overlay click
   */
  const handleOverlayClick = useCallback(
    (e: React.MouseEvent) => {
      if (e.target === e.currentTarget) {
        onClose();
      }
    },
    [onClose]
  );

  /**
   * Clear current image
   */
  const handleClear = useCallback(() => {
    setImageData(null);
    seedAspect(null, null);
    setAltText('');
    setError(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  }, [seedAspect]);

  // Don't render if not open
  if (!isOpen) {
    return null;
  }

  const canInsert =
    imageData !== null &&
    typeof width === 'number' &&
    width > 0 &&
    typeof height === 'number' &&
    height > 0;

  // Get drop zone style
  const getDropZoneStyle = (): CSSProperties => {
    if (imageData) return DROP_ZONE_WITH_IMAGE_STYLE;
    if (isDragging) return DROP_ZONE_ACTIVE_STYLE;
    return DROP_ZONE_STYLE;
  };

  return (
    <div
      className={`docx-insert-image-dialog-overlay ${className || ''}`}
      style={{ ...DIALOG_OVERLAY_STYLE, ...style }}
      onClick={handleOverlayClick}
      onKeyDown={handleKeyDown}
      role="dialog"
      aria-modal="true"
      aria-labelledby="insert-image-dialog-title"
    >
      <div
        ref={dialogRef}
        className="docx-insert-image-dialog"
        style={DIALOG_CONTENT_STYLE}
        tabIndex={-1}
      >
        {/* Header */}
        <div className="docx-insert-image-dialog-header" style={DIALOG_HEADER_STYLE}>
          <h2 id="insert-image-dialog-title" style={DIALOG_TITLE_STYLE}>
            {t('dialogs.insertImage.title')}
          </h2>
          <button
            type="button"
            className="docx-insert-image-dialog-close"
            style={CLOSE_BUTTON_STYLE}
            onClick={onClose}
            aria-label={t('common.closeDialog')}
          >
            &times;
          </button>
        </div>

        {/* Body */}
        <div className="docx-insert-image-dialog-body" style={DIALOG_BODY_STYLE}>
          {/* Hidden file input */}
          <input
            ref={fileInputRef}
            type="file"
            accept={accept}
            onChange={handleFileChange}
            style={{ display: 'none' }}
          />

          {/* Drop zone / Preview */}
          <div
            className="docx-insert-image-dropzone"
            style={getDropZoneStyle()}
            onClick={handleDropZoneClick}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            role="button"
            tabIndex={0}
            aria-label={t('dialogs.insertImage.uploadAriaLabel')}
          >
            {imageData ? (
              <div style={PREVIEW_CONTAINER_STYLE}>
                <img src={imageData.src} alt={altText || 'Preview'} style={PREVIEW_IMAGE_STYLE} />
              </div>
            ) : (
              <>
                <div style={DROP_ZONE_ICON_STYLE}>
                  <ImageIcon />
                </div>
                <div style={DROP_ZONE_TEXT_STYLE}>{t('dialogs.insertImage.uploadText')}</div>
                <div style={DROP_ZONE_SUBTEXT_STYLE}>{t('dialogs.insertImage.uploadSubtext')}</div>
              </>
            )}
          </div>

          {/* Error message */}
          {error && (
            <div
              style={{
                color: 'var(--doc-error)',
                fontSize: '14px',
                marginBottom: '16px',
                textAlign: 'center',
              }}
            >
              {error}
            </div>
          )}

          {imageData && (
            <>
              <div style={SIZE_ROW_STYLE}>
                <label style={INLINE_LABEL_STYLE}>
                  {t('dialogs.insertImage.widthLabel')}
                  <input
                    type="number"
                    value={width}
                    onChange={(e) => handleWidthChange(e.target.value)}
                    min={1}
                    max={maxWidth}
                    style={SIZE_INPUT_STYLE}
                  />
                </label>
                <label style={INLINE_LABEL_STYLE}>
                  {t('dialogs.insertImage.heightLabel')}
                  <input
                    type="number"
                    value={height}
                    onChange={(e) => handleHeightChange(e.target.value)}
                    min={1}
                    max={maxHeight}
                    style={SIZE_INPUT_STYLE}
                  />
                </label>
                <label style={LOCK_LABEL_STYLE}>
                  <input
                    type="checkbox"
                    checked={aspectLocked}
                    onChange={(e) => setAspectLocked(e.target.checked)}
                  />
                  {aspectLocked
                    ? t('dialogs.insertImage.aspectRatioLocked')
                    : t('dialogs.insertImage.aspectRatioUnlocked')}
                </label>
              </div>

              <div style={FORM_GROUP_STYLE}>
                <label htmlFor="insert-image-alt" style={LABEL_STYLE}>
                  {t('dialogs.insertImage.altTextLabel')}
                </label>
                <input
                  id="insert-image-alt"
                  type="text"
                  value={altText}
                  onChange={(e) => setAltText(e.target.value)}
                  placeholder={t('dialogs.insertImage.altTextPlaceholder')}
                  style={INPUT_STYLE}
                />
              </div>
            </>
          )}
        </div>

        <div className="docx-insert-image-dialog-footer" style={DIALOG_FOOTER_STYLE}>
          {(() => {
            const hasImage = imageData !== null;
            return (
              <button
                type="button"
                className="docx-insert-image-dialog-clear"
                style={SECONDARY_BUTTON_STYLE}
                onClick={hasImage ? handleClear : onClose}
              >
                {hasImage ? t('common.clear') : t('common.cancel')}
              </button>
            );
          })()}
          <button
            type="button"
            className="docx-insert-image-dialog-insert"
            style={canInsert ? PRIMARY_BUTTON_STYLE : DISABLED_BUTTON_STYLE}
            onClick={handleInsert}
            disabled={!canInsert}
          >
            {t('dialogs.insertImage.insertButton')}
          </button>
        </div>
      </div>
    </div>
  );
}

// ============================================================================
// HOOK
// ============================================================================

/**
 * Hook for managing Insert Image dialog state
 */
export function useInsertImageDialog(): {
  isOpen: boolean;
  open: () => void;
  close: () => void;
  toggle: () => void;
} {
  const [isOpen, setIsOpen] = useState(false);

  const open = useCallback(() => setIsOpen(true), []);
  const close = useCallback(() => setIsOpen(false), []);
  const toggle = useCallback(() => setIsOpen((prev) => !prev), []);

  return { isOpen, open, close, toggle };
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Check if a file is a valid image
 */
export function isValidImageFile(file: File): boolean {
  return file.type.startsWith('image/');
}

/**
 * Get supported image extensions
 */
export function getSupportedImageExtensions(): string[] {
  return ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.bmp', '.svg'];
}

/**
 * Get accept string for file input
 */
export function getImageAcceptString(): string {
  return 'image/png,image/jpeg,image/gif,image/webp,image/bmp,image/svg+xml';
}

/**
 * Calculate scaled dimensions to fit within bounds
 */
export function calculateFitDimensions(
  originalWidth: number,
  originalHeight: number,
  maxWidth: number,
  maxHeight: number
): { width: number; height: number } {
  if (originalWidth <= maxWidth && originalHeight <= maxHeight) {
    return { width: originalWidth, height: originalHeight };
  }

  const scaleX = maxWidth / originalWidth;
  const scaleY = maxHeight / originalHeight;
  const scale = Math.min(scaleX, scaleY);

  return {
    width: Math.round(originalWidth * scale),
    height: Math.round(originalHeight * scale),
  };
}

/**
 * Convert data URL to Blob
 */
export function dataUrlToBlob(dataUrl: string): Blob {
  const parts = dataUrl.split(',');
  const mime = parts[0].match(/:(.*?);/)?.[1] || 'image/png';
  const binaryString = atob(parts[1]);
  const bytes = new Uint8Array(binaryString.length);

  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }

  return new Blob([bytes], { type: mime });
}

/**
 * Get image dimensions from a data URL
 */
export function getImageDimensions(src: string): Promise<{ width: number; height: number }> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve({ width: img.width, height: img.height });
    img.onerror = () => reject(new Error('Failed to load image'));
    img.src = src;
  });
}

/**
 * Format file size for display
 */
export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// ============================================================================
// EXPORTS
// ============================================================================

export default InsertImageDialog;
