// packages/vue/src/components/dialogs/SplitCellDialog.vue
<!--
  Vue port of packages/react/src/components/dialogs/SplitCellDialog.tsx —
  modal dialog with two number inputs for rows × columns, applied via
  emit('apply', rows, cols).
-->
<template>
  <div v-if="isOpen" class="docx-split-cell" @click.self="$emit('close')">
    <div class="docx-split-cell__dialog">
      <div class="docx-split-cell__header">{{ t('dialogs.splitCell.title') }}</div>
      <div class="docx-split-cell__body">
        <label class="docx-split-cell__row">
          <span class="docx-split-cell__label">{{ t('dialogs.splitCell.rowsLabel') }}</span>
          <input
            v-model.number="rows"
            type="number"
            class="docx-split-cell__input"
            :min="minRows"
            :max="20"
            @keydown.enter.prevent="apply"
          />
        </label>
        <label class="docx-split-cell__row">
          <span class="docx-split-cell__label">{{ t('dialogs.splitCell.columnsLabel') }}</span>
          <input
            v-model.number="cols"
            type="number"
            class="docx-split-cell__input"
            :min="minCols"
            :max="20"
            @keydown.enter.prevent="apply"
          />
        </label>
      </div>
      <div class="docx-split-cell__footer">
        <button class="docx-split-cell__cancel" @click="$emit('close')">{{ t('common.cancel') }}</button>
        <button class="docx-split-cell__apply" :disabled="!valid" @click="apply">{{ t('common.apply') }}</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useTranslation } from '../../i18n';

const { t } = useTranslation();

const props = withDefaults(
  defineProps<{
    isOpen: boolean;
    initialRows?: number;
    initialCols?: number;
    minRows?: number;
    minCols?: number;
  }>(),
  { initialRows: 1, initialCols: 2, minRows: 1, minCols: 1 }
);

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'apply', rows: number, cols: number): void;
}>();

const rows = ref(props.initialRows);
const cols = ref(props.initialCols);

watch(
  () => props.isOpen,
  (open) => {
    if (open) {
      rows.value = props.initialRows;
      cols.value = props.initialCols;
    }
  }
);

const valid = computed(
  () =>
    Number.isFinite(rows.value) &&
    Number.isFinite(cols.value) &&
    rows.value >= props.minRows &&
    cols.value >= props.minCols &&
    rows.value * cols.value > 1
);

function apply() {
  if (!valid.value) return;
  emit('apply', rows.value, cols.value);
}
</script>

<style scoped>
.docx-split-cell {
  position: fixed;
  inset: 0;
  background: var(--doc-overlay);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10000;
}
.docx-split-cell__dialog {
  background: var(--doc-surface);
  border-radius: 8px;
  box-shadow: 0 4px 20px var(--doc-shadow);
  min-width: 360px;
  max-width: 440px;
  width: 100%;
  margin: 20px;
}
.docx-split-cell__header {
  padding: 16px 20px 12px;
  border-bottom: 1px solid var(--doc-border);
  font-size: 16px;
  font-weight: 600;
}
.docx-split-cell__body {
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.docx-split-cell__row {
  display: flex;
  align-items: center;
  gap: 12px;
}
.docx-split-cell__label {
  width: 160px;
  font-size: 13px;
  color: var(--doc-text);
}
.docx-split-cell__input {
  flex: 1;
  height: 32px;
  border: 1px solid var(--doc-border-dark);
  border-radius: 4px;
  padding: 0 8px;
  font-size: 13px;
}
.docx-split-cell__footer {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  padding: 12px 20px 16px;
}
.docx-split-cell__cancel,
.docx-split-cell__apply {
  padding: 6px 16px;
  font-size: 14px;
  border-radius: 4px;
  cursor: pointer;
  border: 1px solid var(--doc-border-dark);
  background: var(--doc-surface);
}
.docx-split-cell__apply {
  background: var(--doc-primary);
  border-color: var(--doc-primary);
  color: var(--doc-on-primary);
}
.docx-split-cell__apply:disabled {
  background: var(--doc-bg-hover);
  border-color: var(--doc-bg-hover);
  color: var(--doc-text-subtle);
  cursor: not-allowed;
}
</style>

// packages/react/src/components/dialogs/SplitCellDialog.tsx
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { useTranslation } from '../../i18n';

export interface SplitCellDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onApply: (rows: number, cols: number) => void;
  initialRows?: number;
  initialCols?: number;
  minRows?: number;
  minCols?: number;
}

const overlayStyle: CSSProperties = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'var(--doc-overlay)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 10000,
};

const dialogStyle: CSSProperties = {
  backgroundColor: 'var(--doc-surface)',
  borderRadius: 8,
  boxShadow: '0 4px 20px var(--doc-shadow)',
  minWidth: 360,
  maxWidth: 440,
  width: '100%',
  margin: 20,
};

const headerStyle: CSSProperties = {
  padding: '16px 20px 12px',
  borderBottom: '1px solid var(--doc-border)',
  fontSize: 16,
  fontWeight: 600,
};

const bodyStyle: CSSProperties = {
  padding: '16px 20px',
  display: 'flex',
  flexDirection: 'column',
  gap: 12,
};

const rowStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 12,
};

const labelStyle: CSSProperties = {
  width: 88,
  fontSize: 13,
  color: 'var(--doc-text-muted)',
};

const inputStyle: CSSProperties = {
  flex: 1,
  padding: '6px 8px',
  border: '1px solid var(--doc-border)',
  borderRadius: 4,
  fontSize: 13,
};

const helperStyle: CSSProperties = {
  fontSize: 12,
  color: 'var(--doc-text-muted)',
  lineHeight: 1.5,
};

const errorStyle: CSSProperties = {
  ...helperStyle,
  color: 'var(--doc-error)',
};

const footerStyle: CSSProperties = {
  padding: '12px 20px 16px',
  borderTop: '1px solid var(--doc-border)',
  display: 'flex',
  justifyContent: 'flex-end',
  gap: 8,
};

const btnStyle: CSSProperties = {
  padding: '6px 16px',
  fontSize: 13,
  border: '1px solid var(--doc-border)',
  borderRadius: 4,
  cursor: 'pointer',
};

export function SplitCellDialog({
  isOpen,
  onClose,
  onApply,
  initialRows = 1,
  initialCols = 1,
  minRows = 1,
  minCols = 1,
}: SplitCellDialogProps): React.ReactElement | null {
  const { t } = useTranslation();
  const [rows, setRows] = useState(initialRows);
  const [cols, setCols] = useState(initialCols);

  useEffect(() => {
    if (isOpen) {
      setRows(initialRows);
      setCols(initialCols);
    }
  }, [initialCols, initialRows, isOpen]);

  const validationError = useMemo(() => {
    if (rows < minRows || cols < minCols) {
      return t('dialogs.splitCell.minValue', { rows: minRows, cols: minCols });
    }
    if (rows === 1 && cols === 1) {
      return t('dialogs.splitCell.notOneByOne');
    }
    return null;
  }, [cols, minCols, minRows, rows, t]);

  const handleApply = useCallback(() => {
    if (validationError) return;
    onApply(rows, cols);
    onClose();
  }, [cols, onApply, onClose, rows, validationError]);

  const handleKeyDown = useCallback(
    (event: React.KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
      if (event.key === 'Enter') handleApply();
    },
    [handleApply, onClose]
  );

  if (!isOpen) return null;

  return (
    <div
      style={overlayStyle}
      onClick={onClose}
      onKeyDown={handleKeyDown}
      onMouseDown={(event) => event.stopPropagation()}
    >
      <div
        style={dialogStyle}
        onClick={(event) => event.stopPropagation()}
        role="dialog"
        aria-label={t('dialogs.splitCell.title')}
      >
        <div style={headerStyle}>{t('dialogs.splitCell.title')}</div>

        <div style={bodyStyle}>
          <div style={helperStyle}>{t('dialogs.splitCell.description')}</div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.splitCell.rowsLabel')}</label>
            <input
              type="number"
              style={inputStyle}
              min={minRows}
              step={1}
              value={rows}
              onChange={(event) => setRows(Math.max(0, Number(event.target.value) || 0))}
            />
          </div>

          <div style={rowStyle}>
            <label style={labelStyle}>{t('dialogs.splitCell.columnsLabel')}</label>
            <input
              type="number"
              style={inputStyle}
              min={minCols}
              step={1}
              value={cols}
              onChange={(event) => setCols(Math.max(0, Number(event.target.value) || 0))}
            />
          </div>

          <div style={validationError ? errorStyle : helperStyle}>
            {validationError ??
              t('dialogs.splitCell.currentMinimum', { rows: minRows, cols: minCols })}
          </div>
        </div>

        <div style={footerStyle}>
          <button type="button" style={btnStyle} onClick={onClose}>
            {t('common.cancel')}
          </button>
          <button
            type="button"
            style={{
              ...btnStyle,
              backgroundColor: 'var(--doc-primary)',
              color: 'var(--doc-on-primary)',
              borderColor: 'var(--doc-primary)',
              opacity: validationError ? 0.6 : 1,
              cursor: validationError ? 'not-allowed' : 'pointer',
            }}
            disabled={!!validationError}
            onClick={handleApply}
          >
            {t('common.apply')}
          </button>
        </div>
      </div>
    </div>
  );
}

export default SplitCellDialog;
