// packages/react/src/components/ui/MenuDropdown.tsx
/**
 * MenuDropdown — a reusable dropdown menu with text label trigger
 *
 * Uses position:fixed so dropdowns escape overflow:auto/hidden ancestors.
 * Supports submenu panels that appear to the right on hover (Google Docs style).
 */

import { useState, useRef, useEffect, useCallback } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import { MaterialSymbol } from './MaterialSymbol';

export interface MenuItem {
  icon?: string;
  label: string;
  shortcut?: string;
  onClick?: () => void;
  disabled?: boolean;
  /** Custom content to render instead of a simple menu item */
  customContent?: ReactNode;
  /** Submenu content that appears to the right on hover */
  submenuContent?: (closeMenu: () => void) => ReactNode;
}

export interface MenuSeparator {
  type: 'separator';
}

export type MenuEntry = MenuItem | MenuSeparator;

function isSeparator(entry: MenuEntry): entry is MenuSeparator {
  return 'type' in entry && entry.type === 'separator';
}

interface MenuDropdownProps {
  label: string;
  items: MenuEntry[];
  disabled?: boolean;
  /** When true, the trigger renders a down-arrow caret next to the label.
   *  Default `false` — every in-tree caller is a top-level menubar button. */
  showChevron?: boolean;
}

const triggerStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 2,
  padding: '2px 8px',
  border: 'none',
  background: 'transparent',
  borderRadius: 4,
  cursor: 'pointer',
  fontSize: 13,
  fontWeight: 400,
  color: 'var(--doc-text, #374151)',
  whiteSpace: 'nowrap',
  height: 28,
  lineHeight: '28px',
};

const triggerOpenStyle: CSSProperties = {
  ...triggerStyle,
  background: 'var(--doc-hover, #f3f4f6)',
};

const menuItemStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  padding: '6px 12px',
  border: 'none',
  background: 'transparent',
  cursor: 'pointer',
  fontSize: 13,
  color: 'var(--doc-text, #374151)',
  width: '100%',
  textAlign: 'left',
  whiteSpace: 'nowrap',
};

const menuItemDisabledStyle: CSSProperties = {
  ...menuItemStyle,
  opacity: 0.4,
  cursor: 'default',
};

const separatorStyle: CSSProperties = {
  height: 1,
  backgroundColor: 'var(--doc-border, #e5e7eb)',
  margin: '4px 0',
};

const shortcutStyle: CSSProperties = {
  marginLeft: 'auto',
  fontSize: 12,
  color: 'var(--doc-text-muted, #9ca3af)',
};

const submenuPanelStyle: CSSProperties = {
  position: 'absolute',
  left: '100%',
  top: -4,
  marginLeft: 2,
  backgroundColor: 'white',
  border: '1px solid var(--doc-border, #d1d5db)',
  borderRadius: 6,
  boxShadow: '0 4px 12px rgba(0, 0, 0, 0.12)',
  padding: 8,
  zIndex: 1001,
};

export function MenuDropdown({ label, items, disabled, showChevron = false }: MenuDropdownProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [hoveredSubmenu, setHoveredSubmenu] = useState<string | null>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const [dropdownPos, setDropdownPos] = useState<{ top: number; left: number }>({
    top: 0,
    left: 0,
  });

  const closeMenu = useCallback(() => {
    setIsOpen(false);
    setHoveredSubmenu(null);
  }, []);

  // Calculate position when opening
  useEffect(() => {
    if (!isOpen || !triggerRef.current) return;
    const rect = triggerRef.current.getBoundingClientRect();
    setDropdownPos({ top: rect.bottom + 2, left: rect.left });
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;

    function handleClickOutside(e: MouseEvent) {
      const target = e.target as Node;
      if (
        triggerRef.current &&
        !triggerRef.current.contains(target) &&
        dropdownRef.current &&
        !dropdownRef.current.contains(target)
      ) {
        closeMenu();
      }
    }

    function handleEscape(e: KeyboardEvent) {
      if (e.key === 'Escape') closeMenu();
    }

    // Close on scroll of any ancestor (dropdown position would be stale)
    function handleScroll() {
      closeMenu();
    }

    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleEscape);
    window.addEventListener('scroll', handleScroll, true);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
      window.removeEventListener('scroll', handleScroll, true);
    };
  }, [isOpen, closeMenu]);

  const handleItemClick = (item: MenuItem) => {
    if (item.disabled || item.submenuContent) return;
    if (!item.onClick) return;
    item.onClick();
    closeMenu();
  };

  return (
    <div style={{ position: 'relative' }}>
      <button
        ref={triggerRef}
        type="button"
        onClick={() => !disabled && setIsOpen(!isOpen)}
        onMouseDown={(e) => e.preventDefault()}
        disabled={disabled}
        style={isOpen ? triggerOpenStyle : triggerStyle}
      >
        {label}
        {showChevron && <MaterialSymbol name="arrow_drop_down" size={16} />}
      </button>

      {isOpen && (
        <div
          ref={dropdownRef}
          style={{
            position: 'fixed',
            top: dropdownPos.top,
            left: dropdownPos.left,
            backgroundColor: 'white',
            border: '1px solid var(--doc-border, #d1d5db)',
            borderRadius: 6,
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.12)',
            padding: '4px 0',
            zIndex: 10000,
            minWidth: 200,
          }}
          onMouseDown={(e) => e.preventDefault()}
        >
          {items.map((entry, i) => {
            if (isSeparator(entry)) {
              return <div key={`sep-${i}`} style={separatorStyle} />;
            }
            const item = entry;
            if (item.customContent) {
              return (
                <div key={item.label} onMouseDown={(e) => e.preventDefault()}>
                  {item.customContent}
                </div>
              );
            }

            const hasSubmenu = !!item.submenuContent;
            const isSubmenuOpen = hoveredSubmenu === item.label;

            return (
              <div
                key={item.label}
                style={{ position: 'relative' }}
                onMouseEnter={() => hasSubmenu && setHoveredSubmenu(item.label)}
                onMouseLeave={() => hasSubmenu && setHoveredSubmenu(null)}
              >
                <button
                  type="button"
                  style={item.disabled ? menuItemDisabledStyle : menuItemStyle}
                  onClick={() => handleItemClick(item)}
                  onMouseDown={(e) => e.preventDefault()}
                  onMouseOver={(e) => {
                    if (!item.disabled) {
                      (e.currentTarget as HTMLButtonElement).style.backgroundColor =
                        'var(--doc-hover, #f3f4f6)';
                    }
                  }}
                  onMouseOut={(e) => {
                    (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'transparent';
                  }}
                  disabled={item.disabled}
                >
                  {item.icon && <MaterialSymbol name={item.icon} size={18} />}
                  <span>{item.label}</span>
                  {item.shortcut && <span style={shortcutStyle}>{item.shortcut}</span>}
                  {hasSubmenu && (
                    <span style={{ marginLeft: 'auto' }}>
                      <MaterialSymbol name="keyboard_arrow_right" size={16} />
                    </span>
                  )}
                </button>
                {hasSubmenu && isSubmenuOpen && (
                  <div style={submenuPanelStyle} onMouseDown={(e) => e.preventDefault()}>
                    {item.submenuContent!(closeMenu)}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

// packages/vue/src/components/ui/MenuDropdown.vue
<!-- Dropdown menu with a text-label trigger — Vue port of
     packages/react/src/components/ui/MenuDropdown.tsx (same `MenuEntry` shape).
     Items with `submenu: true` open a hover panel from the `#submenu` slot. -->
<template>
  <Popover :open="isOpen" @update:open="(v) => (isOpen = v)" @close="closeMenu">
    <template #trigger="{ toggle }">
      <button
        type="button"
        class="docx-menu-dropdown__trigger"
        :class="{ 'docx-menu-dropdown__trigger--open': isOpen }"
        :disabled="disabled"
        @mousedown.prevent
        @click.prevent="toggle"
      >
        {{ label }}
        <MaterialSymbol v-if="showChevron" name="arrow_drop_down" :size="16" />
      </button>
    </template>
    <template #panel>
      <!-- @mousedown.prevent so picking an item doesn't blur the ProseMirror view
           (the menu only contains buttons + the table grid, no inputs). -->
      <div class="docx-menu-dropdown__menu" @mousedown.prevent>
        <template v-for="(item, i) in items" :key="i">
          <div v-if="isSeparator(item)" class="docx-menu-dropdown__separator" />
          <div
            v-else
            class="docx-menu-dropdown__wrap"
            @mouseenter="item.submenu ? (openSubmenu = i) : undefined"
            @mouseleave="item.submenu ? (openSubmenu = null) : undefined"
          >
            <button
              type="button"
              class="docx-menu-dropdown__item"
              :class="{ 'docx-menu-dropdown__item--disabled': item.disabled }"
              :disabled="item.disabled"
              @click.prevent="onItemClick(item)"
            >
              <MaterialSymbol v-if="item.icon" :name="item.icon" :size="18" />
              <span class="docx-menu-dropdown__label">{{ item.label }}</span>
              <span v-if="item.shortcut" class="docx-menu-dropdown__shortcut">{{
                item.shortcut
              }}</span>
              <span v-if="item.submenu" class="docx-menu-dropdown__chevron">
                <MaterialSymbol name="keyboard_arrow_right" :size="16" />
              </span>
            </button>
            <div v-if="item.submenu && openSubmenu === i" class="docx-menu-dropdown__submenu">
              <slot name="submenu" :item="item" :close-menu="closeMenu" />
            </div>
          </div>
        </template>
      </div>
    </template>
  </Popover>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import MaterialSymbol from './MaterialSymbol.vue';
import Popover from './Popover.vue';

export interface MenuItem {
  icon?: string;
  label: string;
  shortcut?: string;
  onClick?: () => void;
  disabled?: boolean;
  /** Stable id so the `#submenu` slot can tell which item it's rendering for. */
  key?: string;
  /** When true, the item shows a right-chevron and opens the `#submenu` slot on hover. */
  submenu?: boolean;
}
export interface MenuSeparator {
  type: 'separator';
}
export type MenuEntry = MenuItem | MenuSeparator;

function isSeparator(entry: MenuEntry): entry is MenuSeparator {
  return 'type' in entry && entry.type === 'separator';
}

withDefaults(
  defineProps<{
    label: string;
    items: MenuEntry[];
    disabled?: boolean;
    /** When true, the trigger renders a down-arrow caret next to the label.
     *  Default `false` — every in-tree caller is a top-level menubar button. */
    showChevron?: boolean;
  }>(),
  { showChevron: false }
);

const isOpen = ref(false);
const openSubmenu = ref<number | null>(null);

function closeMenu() {
  isOpen.value = false;
  openSubmenu.value = null;
}

function onItemClick(item: MenuItem) {
  if (item.disabled || item.submenu) return;
  item.onClick?.();
  closeMenu();
}
</script>

<style scoped>
.docx-menu-dropdown__trigger {
  display: flex;
  align-items: center;
  gap: 2px;
  padding: 2px 8px;
  border: none;
  background: transparent;
  border-radius: 4px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 400;
  color: #374151;
  white-space: nowrap;
  height: 28px;
}
.docx-menu-dropdown__trigger:hover {
  background: #f3f4f6;
}
.docx-menu-dropdown__trigger--open {
  background: #f3f4f6;
}
.docx-menu-dropdown__menu {
  min-width: 200px;
  padding: 4px 0;
}
.docx-menu-dropdown__wrap {
  position: relative;
}
.docx-menu-dropdown__item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 13px;
  color: #374151;
  width: 100%;
  text-align: left;
  white-space: nowrap;
}
.docx-menu-dropdown__item:hover:not(.docx-menu-dropdown__item--disabled) {
  background: #f3f4f6;
}
.docx-menu-dropdown__item--disabled {
  opacity: 0.4;
  cursor: default;
}
.docx-menu-dropdown__label {
  flex: 1;
}
.docx-menu-dropdown__shortcut {
  margin-left: auto;
  font-size: 11px;
  color: #9ca3af;
  font-family: monospace;
}
.docx-menu-dropdown__chevron {
  margin-left: auto;
  display: inline-flex;
  color: #9ca3af;
}
.docx-menu-dropdown__submenu {
  /* Flush against the item (no margin) so the cursor never crosses a gap
     that would fire mouseleave and collapse the submenu mid-travel. */
  position: absolute;
  left: 100%;
  top: -4px;
  background: #fff;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.12);
  padding: 8px;
  z-index: 1;
}
.docx-menu-dropdown__separator {
  height: 1px;
  background: #e5e7eb;
  margin: 4px 0;
}
</style>
