// packages/react/src/components/ui/TableInsertButtons.tsx
/**
 * TableInsertButtons - 4 icon buttons for row/column insertion
 *
 * Insert row above, insert row below, insert column left, insert column right.
 */

import React, { useCallback } from 'react';
import { MaterialSymbol } from './MaterialSymbol';
import { Button } from './Button';
import { Tooltip } from './Tooltip';
import { cn } from '../../lib/utils';
import type { TableAction } from './TableToolbar';
import { useTranslation } from '../../i18n';
import type { TranslationKey } from '@sqren/docx-editor-i18n';

export interface TableInsertButtonsProps {
  onAction: (action: TableAction) => void;
  disabled?: boolean;
}

const INSERT_ACTIONS: {
  action: TableAction;
  icon: string;
  labelKey: TranslationKey;
  testId: string;
}[] = [
  {
    action: 'addRowAbove',
    icon: 'keyboard_arrow_up',
    labelKey: 'table.insertRowAbove',
    testId: 'toolbar-table-add-row-above',
  },
  {
    action: 'addRowBelow',
    icon: 'keyboard_arrow_down',
    labelKey: 'table.insertRowBelow',
    testId: 'toolbar-table-add-row-below',
  },
  {
    action: 'addColumnLeft',
    icon: 'keyboard_arrow_left',
    labelKey: 'table.insertColumnLeft',
    testId: 'toolbar-table-add-col-left',
  },
  {
    action: 'addColumnRight',
    icon: 'keyboard_arrow_right',
    labelKey: 'table.insertColumnRight',
    testId: 'toolbar-table-add-col-right',
  },
];

export function TableInsertButtons({ onAction, disabled = false }: TableInsertButtonsProps) {
  const { t } = useTranslation();
  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
  }, []);

  return (
    <>
      {INSERT_ACTIONS.map(({ action, icon, labelKey, testId }) => {
        const label = t(labelKey);
        return (
          <Tooltip key={typeof action === 'string' ? action : action.type} content={label}>
            <Button
              variant="ghost"
              size="icon-sm"
              className={cn(
                'text-muted-foreground hover:text-foreground hover:bg-muted/80',
                disabled && 'opacity-30 cursor-not-allowed'
              )}
              onMouseDown={handleMouseDown}
              onClick={() => !disabled && onAction(action)}
              disabled={disabled}
              aria-label={label}
              data-testid={testId}
            >
              <MaterialSymbol name={icon} size={20} />
            </Button>
          </Tooltip>
        );
      })}
    </>
  );
}

export default TableInsertButtons;

// packages/vue/src/components/ui/TableInsertButtons.vue
<!--
  Vue port of packages/react/src/components/ui/TableInsertButtons.tsx —
  four icon buttons: row above / row below / column left / column right.
  Same emit contract (string action). Caller handles the actual table
  mutation via prosemirror commands.
-->
<template>
  <span class="docx-table-insert">
    <button
      v-for="b in INSERT_ACTIONS"
      :key="b.action"
      type="button"
      class="docx-table-insert__btn"
      :disabled="disabled"
      :title="b.label"
      @click.prevent="emit('action', b.action)"
    >
      <MaterialSymbol :name="b.icon" :size="20" />
    </button>
  </span>
</template>

<script setup lang="ts">
import MaterialSymbol from './MaterialSymbol.vue';

export type TableAction =
  | 'addRowAbove'
  | 'addRowBelow'
  | 'addColumnLeft'
  | 'addColumnRight';

defineProps<{
  disabled?: boolean;
}>();

const emit = defineEmits<{
  (e: 'action', action: TableAction): void;
}>();

const INSERT_ACTIONS: { action: TableAction; icon: string; label: string }[] = [
  { action: 'addRowAbove', icon: 'keyboard_arrow_up', label: 'Insert row above' },
  { action: 'addRowBelow', icon: 'keyboard_arrow_down', label: 'Insert row below' },
  { action: 'addColumnLeft', icon: 'keyboard_arrow_left', label: 'Insert column left' },
  { action: 'addColumnRight', icon: 'keyboard_arrow_right', label: 'Insert column right' },
];
</script>

<style scoped>
.docx-table-insert {
  display: inline-flex;
  gap: 1px;
}
.docx-table-insert__btn {
  width: 28px;
  height: 28px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: none;
  border-radius: 6px;
  background: transparent;
  color: var(--doc-text-muted);
  cursor: pointer;
}
.docx-table-insert__btn:hover:not(:disabled) {
  background: var(--doc-bg-hover);
  color: var(--doc-text);
}
.docx-table-insert__btn:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}
</style>
