// packages/react/src/components/ui/TableBorderPicker.tsx
/**
 * TableBorderPicker - Google Docs-style border preset popover
 *
 * Shows a grid of border preset buttons: All, Outside, Inside,
 * Top, Bottom, Left, Right, and Clear.
 */

import { useState, useCallback } from 'react';
import { Button } from './Button';
import { Tooltip } from './Tooltip';
import { MaterialSymbol } from './MaterialSymbol';
import { cn } from '../../lib/utils';
import type { TableAction } from './TableToolbar';
import { useFixedDropdown } from '../../hooks/useFixedDropdown';
import { useTranslation } from '../../i18n';
import type { TranslationKey } from '@eigenpal/docx-editor-i18n';

export interface TableBorderPickerProps {
  onAction: (action: TableAction) => void;
  disabled?: boolean;
}

const BORDER_PRESETS: { action: TableAction; icon: string; labelKey: TranslationKey }[] = [
  { action: 'borderAll', icon: 'border_all', labelKey: 'table.borders.all' },
  { action: 'borderOutside', icon: 'border_outer', labelKey: 'table.borders.outside' },
  { action: 'borderInside', icon: 'border_inner', labelKey: 'table.borders.inside' },
  { action: 'borderTop', icon: 'border_top', labelKey: 'table.borders.top' },
  { action: 'borderBottom', icon: 'border_bottom', labelKey: 'table.borders.bottom' },
  { action: 'borderLeft', icon: 'border_left', labelKey: 'table.borders.left' },
  { action: 'borderRight', icon: 'border_right', labelKey: 'table.borders.right' },
  { action: 'borderNone', icon: 'border_clear', labelKey: 'table.borders.none' },
];

export function TableBorderPicker({ onAction, disabled = false }: TableBorderPickerProps) {
  const { t } = useTranslation();
  const [isOpen, setIsOpen] = useState(false);
  const close = useCallback(() => setIsOpen(false), []);
  const { containerRef, dropdownRef, dropdownStyle, handleMouseDown } = useFixedDropdown({
    isOpen,
    onClose: close,
  });

  const handlePreset = useCallback(
    (action: TableAction) => {
      onAction(action);
      setIsOpen(false);
    },
    [onAction]
  );

  const button = (
    <Button
      variant="ghost"
      size="icon-sm"
      className={cn(
        'text-muted-foreground hover:text-foreground hover:bg-muted/80',
        isOpen && 'bg-muted',
        disabled && 'opacity-30 cursor-not-allowed'
      )}
      onMouseDown={handleMouseDown}
      onClick={() => !disabled && setIsOpen((prev) => !prev)}
      disabled={disabled}
      aria-label={t('table.borders.styleAriaLabel')}
      aria-expanded={isOpen}
      aria-haspopup="true"
      data-testid="toolbar-table-borders"
    >
      <MaterialSymbol name="border_all" size={20} />
      <MaterialSymbol name="arrow_drop_down" size={14} className="-ml-1" />
    </Button>
  );

  return (
    <div ref={containerRef} style={{ position: 'relative', display: 'inline-block' }}>
      {!isOpen ? <Tooltip content={t('table.borders.tooltip')}>{button}</Tooltip> : button}

      {isOpen && !disabled && (
        <div
          ref={dropdownRef}
          style={{
            ...dropdownStyle,
            backgroundColor: 'var(--doc-surface)',
            border: '1px solid var(--doc-border)',
            borderRadius: 8,
            boxShadow: '0 4px 16px var(--doc-shadow)',
            padding: 6,
          }}
          onMouseDown={(e) => e.stopPropagation()}
        >
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(4, 1fr)',
              gap: 2,
            }}
          >
            {BORDER_PRESETS.map(({ action, icon, labelKey }) => (
              <button
                key={typeof action === 'string' ? action : action.type}
                type="button"
                title={t(labelKey)}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  width: 32,
                  height: 32,
                  border: '1px solid transparent',
                  borderRadius: 4,
                  backgroundColor: 'transparent',
                  cursor: 'pointer',
                  color: 'var(--doc-text)',
                }}
                onMouseDown={(e) => e.preventDefault()}
                onMouseEnter={(e) => {
                  (e.currentTarget as HTMLButtonElement).style.backgroundColor =
                    'var(--doc-bg-hover)';
                }}
                onMouseLeave={(e) => {
                  (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'transparent';
                }}
                onClick={() => handlePreset(action)}
              >
                <MaterialSymbol name={icon} size={18} />
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default TableBorderPicker;

// packages/vue/src/components/ui/TableBorderPicker.vue
<!--
  Vue port of packages/react/src/components/ui/TableBorderPicker.tsx —
  toolbar button + grid panel for which sides get a border. Close
  behaviour via shared Popover.
-->
<template>
  <Popover :open="isOpen" @update:open="(v) => (isOpen = v)" @close="isOpen = false">
    <template #trigger="{ toggle }">
      <button
        type="button"
        class="docx-tbp__btn"
        :disabled="disabled"
        title="Borders"
        @click.prevent="toggle"
      >
        <MaterialSymbol name="border_all" :size="20" />
      </button>
    </template>
    <template #panel>
      <div class="docx-tbp__panel">
        <button
          v-for="o in OPTIONS"
          :key="o.value"
          type="button"
          class="docx-tbp__option"
          :title="o.label"
          @click.prevent="pick(o.value)"
        >
          <MaterialSymbol :name="o.icon" :size="20" />
        </button>
      </div>
    </template>
  </Popover>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import MaterialSymbol from './MaterialSymbol.vue';
import Popover from './Popover.vue';

export type TableBorderPreset =
  | 'all'
  | 'none'
  | 'box'
  | 'inside'
  | 'top'
  | 'bottom'
  | 'left'
  | 'right'
  | 'insideH'
  | 'insideV';

defineProps<{ disabled?: boolean }>();

const emit = defineEmits<{
  (e: 'change', preset: TableBorderPreset): void;
}>();

const isOpen = ref(false);

const OPTIONS: { value: TableBorderPreset; icon: string; label: string }[] = [
  { value: 'all', icon: 'border_all', label: 'All borders' },
  { value: 'none', icon: 'border_clear', label: 'No borders' },
  { value: 'box', icon: 'border_outer', label: 'Outside borders' },
  { value: 'inside', icon: 'border_inner', label: 'Inside borders' },
  { value: 'top', icon: 'border_top', label: 'Top border' },
  { value: 'bottom', icon: 'border_bottom', label: 'Bottom border' },
  { value: 'left', icon: 'border_left', label: 'Left border' },
  { value: 'right', icon: 'border_right', label: 'Right border' },
  { value: 'insideH', icon: 'border_horizontal', label: 'Inside horizontal' },
  { value: 'insideV', icon: 'border_vertical', label: 'Inside vertical' },
];

function pick(preset: TableBorderPreset) {
  emit('change', preset);
  isOpen.value = false;
}
</script>

<style scoped>
.docx-tbp__btn {
  width: 28px; height: 28px;
  display: inline-flex; align-items: center; justify-content: center;
  border: none; border-radius: 6px;
  background: transparent; color: var(--doc-text-muted); cursor: pointer;
}
.docx-tbp__btn:hover:not(:disabled) { background: var(--doc-bg-hover); }
.docx-tbp__panel {
  display: grid;
  grid-template-columns: repeat(5, 32px);
  gap: 2px;
  padding: 4px;
}
.docx-tbp__option {
  width: 32px; height: 32px;
  display: inline-flex; align-items: center; justify-content: center;
  border: none; border-radius: 4px;
  background: transparent; color: var(--doc-text-muted); cursor: pointer;
}
.docx-tbp__option:hover { background: var(--doc-bg-hover); }
</style>
