// packages/react/src/components/ui/VerticalRuler.tsx
/**
 * VerticalRuler Component
 *
 * A vertical ruler that displays alongside the document with:
 * - Page height scale with tick marks
 * - Top and bottom margin indicators
 * - Optional dragging to adjust margins
 * - Support for zoom levels
 *
 * Similar to Google Docs' vertical ruler.
 */

import React, { useState, useRef, useCallback, useEffect } from 'react';
import type { CSSProperties } from 'react';
import type { SectionProperties } from '@sqren/docx-editor-core/types/document';
import { twipsToPixels, pixelsToTwips, formatPx } from '@sqren/docx-editor-core/utils';
import { useTranslation } from '../../i18n';

// ============================================================================
// TYPES
// ============================================================================

export interface VerticalRulerProps {
  /** Section properties for page layout */
  sectionProps?: SectionProperties | null;
  /** Zoom level (1.0 = 100%) */
  zoom?: number;
  /** Whether margins can be dragged to adjust */
  editable?: boolean;
  /** Callback when top margin changes (in twips) */
  onTopMarginChange?: (marginTwips: number) => void;
  /** Callback when bottom margin changes (in twips) */
  onBottomMarginChange?: (marginTwips: number) => void;
  /** Unit to display (inches or cm) */
  unit?: 'inch' | 'cm';
  /** Additional CSS class name */
  className?: string;
  /** Additional inline styles */
  style?: CSSProperties;
}

type MarkerType = 'topMargin' | 'bottomMargin';

// ============================================================================
// CONSTANTS
// ============================================================================

const DEFAULT_PAGE_HEIGHT_TWIPS = 15840; // 11 inches
const DEFAULT_MARGIN_TWIPS = 1440; // 1 inch
const TWIPS_PER_INCH = 1440;
const TWIPS_PER_CM = 567;

// Ruler styling - Google Docs style
const RULER_WIDTH = 20;
const RULER_TEXT_COLOR = 'var(--doc-text-muted)';
const RULER_TICK_COLOR = 'var(--doc-text-subtle)';
const MARKER_COLOR = 'var(--doc-primary)';
const MARKER_HOVER_COLOR = 'var(--doc-primary)';
const MARKER_ACTIVE_COLOR = 'var(--doc-primary-hover)';

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function VerticalRuler({
  sectionProps,
  zoom = 1,
  editable = false,
  onTopMarginChange,
  onBottomMarginChange,
  unit = 'inch',
  className = '',
  style,
}: VerticalRulerProps): React.ReactElement {
  const { t } = useTranslation();
  const [dragging, setDragging] = useState<MarkerType | null>(null);
  const [hoveredMarker, setHoveredMarker] = useState<MarkerType | null>(null);
  const rulerRef = useRef<HTMLDivElement>(null);

  // Get page dimensions
  const pageHeightTwips = sectionProps?.pageHeight ?? DEFAULT_PAGE_HEIGHT_TWIPS;
  const topMarginTwips = sectionProps?.marginTop ?? DEFAULT_MARGIN_TWIPS;
  const bottomMarginTwips = sectionProps?.marginBottom ?? DEFAULT_MARGIN_TWIPS;

  // Convert to pixels with zoom
  const pageHeightPx = twipsToPixels(pageHeightTwips) * zoom;
  const topMarginPx = twipsToPixels(topMarginTwips) * zoom;
  const bottomMarginPx = twipsToPixels(bottomMarginTwips) * zoom;

  // Handle drag start
  const handleDragStart = useCallback(
    (e: React.MouseEvent, marker: MarkerType) => {
      if (!editable) return;
      e.preventDefault();
      setDragging(marker);
    },
    [editable]
  );

  // Handle drag
  const handleDrag = useCallback(
    (e: MouseEvent) => {
      if (!dragging || !rulerRef.current) return;

      const rect = rulerRef.current.getBoundingClientRect();
      const y = e.clientY - rect.top;

      const positionTwips = pixelsToTwips(y / zoom);

      if (dragging === 'topMargin') {
        const maxMargin = pageHeightTwips - bottomMarginTwips - 720;
        const newMargin = Math.max(0, Math.min(positionTwips, maxMargin));
        onTopMarginChange?.(Math.round(newMargin));
      } else if (dragging === 'bottomMargin') {
        const fromBottom = pageHeightTwips - positionTwips;
        const maxMargin = pageHeightTwips - topMarginTwips - 720;
        const newMargin = Math.max(0, Math.min(fromBottom, maxMargin));
        onBottomMarginChange?.(Math.round(newMargin));
      }
    },
    [
      dragging,
      zoom,
      pageHeightTwips,
      topMarginTwips,
      bottomMarginTwips,
      onTopMarginChange,
      onBottomMarginChange,
    ]
  );

  // Handle drag end
  const handleDragEnd = useCallback(() => {
    setDragging(null);
  }, []);

  // Add/remove document event listeners
  useEffect(() => {
    if (dragging) {
      document.addEventListener('mousemove', handleDrag);
      document.addEventListener('mouseup', handleDragEnd);
      return () => {
        document.removeEventListener('mousemove', handleDrag);
        document.removeEventListener('mouseup', handleDragEnd);
      };
    }
  }, [dragging, handleDrag, handleDragEnd]);

  // Generate tick marks
  const ticks = generateVerticalTicks(pageHeightTwips, zoom, unit);

  const rulerStyle: CSSProperties = {
    position: 'relative',
    width: RULER_WIDTH,
    height: formatPx(pageHeightPx),
    backgroundColor: 'transparent',
    overflow: 'visible',
    userSelect: 'none',
    cursor: dragging ? 'ns-resize' : 'default',
    ...style,
  };

  return (
    <div
      ref={rulerRef}
      className={`docx-vertical-ruler ${className}`}
      style={rulerStyle}
      role="slider"
      aria-label={t('ruler.vertical')}
      aria-orientation="vertical"
    >
      {/* Tick marks */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          pointerEvents: 'none',
        }}
      >
        {ticks.map((tick, index) => (
          <VerticalTick key={index} tick={tick} />
        ))}
      </div>

      {/* Top margin marker */}
      <VerticalMarginMarker
        type="topMargin"
        position={topMarginPx}
        editable={editable}
        isDragging={dragging === 'topMargin'}
        isHovered={hoveredMarker === 'topMargin'}
        onMouseEnter={() => setHoveredMarker('topMargin')}
        onMouseLeave={() => setHoveredMarker(null)}
        onMouseDown={(e) => handleDragStart(e, 'topMargin')}
      />

      {/* Bottom margin marker */}
      <VerticalMarginMarker
        type="bottomMargin"
        position={pageHeightPx - bottomMarginPx}
        editable={editable}
        isDragging={dragging === 'bottomMargin'}
        isHovered={hoveredMarker === 'bottomMargin'}
        onMouseEnter={() => setHoveredMarker('bottomMargin')}
        onMouseLeave={() => setHoveredMarker(null)}
        onMouseDown={(e) => handleDragStart(e, 'bottomMargin')}
      />
    </div>
  );
}

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

interface VerticalTickData {
  position: number;
  width: number;
  label?: string;
}

function VerticalTick({ tick }: { tick: VerticalTickData }): React.ReactElement {
  const tickStyle: CSSProperties = {
    position: 'absolute',
    top: formatPx(tick.position),
    right: 0,
    height: 1,
    width: tick.width,
    backgroundColor: RULER_TICK_COLOR,
  };

  const labelStyle: CSSProperties = {
    position: 'absolute',
    top: formatPx(tick.position),
    left: 2,
    transform: 'translateY(-50%)',
    fontSize: '9px',
    color: RULER_TEXT_COLOR,
    fontFamily: 'sans-serif',
    whiteSpace: 'nowrap',
  };

  return (
    <>
      <div style={tickStyle} />
      {tick.label && <div style={labelStyle}>{tick.label}</div>}
    </>
  );
}

interface VerticalMarginMarkerProps {
  type: 'topMargin' | 'bottomMargin';
  position: number;
  editable: boolean;
  isDragging: boolean;
  isHovered: boolean;
  onMouseEnter: () => void;
  onMouseLeave: () => void;
  onMouseDown: (e: React.MouseEvent) => void;
}

function VerticalMarginMarker({
  type,
  position,
  editable,
  isDragging,
  isHovered,
  onMouseEnter,
  onMouseLeave,
  onMouseDown,
}: VerticalMarginMarkerProps): React.ReactElement {
  const { t } = useTranslation();
  const color = isDragging ? MARKER_ACTIVE_COLOR : isHovered ? MARKER_HOVER_COLOR : MARKER_COLOR;

  const markerStyle: CSSProperties = {
    position: 'absolute',
    top: formatPx(position - 5),
    right: 0,
    width: RULER_WIDTH,
    height: 10,
    cursor: editable ? 'ns-resize' : 'default',
    zIndex: isDragging ? 10 : 1,
  };

  // Triangle pointing left (for top) or right (for bottom)
  const triangleStyle: CSSProperties = {
    position: 'absolute',
    top: 0,
    right: 2,
    width: 0,
    height: 0,
    borderTop: '5px solid transparent',
    borderBottom: '5px solid transparent',
    borderRight: `8px solid ${color}`,
    transition: 'border-right-color 0.1s',
  };

  return (
    <div
      className={`docx-ruler-marker docx-ruler-marker-${type}`}
      style={markerStyle}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onMouseDown={onMouseDown}
      role="slider"
      aria-label={type === 'topMargin' ? t('ruler.topMargin') : t('ruler.bottomMargin')}
      aria-orientation="vertical"
      tabIndex={editable ? 0 : -1}
    >
      <div style={triangleStyle} />
    </div>
  );
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

function generateVerticalTicks(
  pageHeightTwips: number,
  zoom: number,
  unit: 'inch' | 'cm'
): VerticalTickData[] {
  const ticks: VerticalTickData[] = [];

  if (unit === 'inch') {
    const eighthInchTwips = TWIPS_PER_INCH / 8;
    const totalEighths = Math.ceil(pageHeightTwips / eighthInchTwips);

    for (let i = 0; i <= totalEighths; i++) {
      const twipsPos = i * eighthInchTwips;
      if (twipsPos > pageHeightTwips) break;

      const pxPos = twipsToPixels(twipsPos) * zoom;

      if (i % 8 === 0) {
        const inches = i / 8;
        ticks.push({
          position: pxPos,
          width: 10,
          label: inches > 0 ? String(inches) : undefined,
        });
      } else if (i % 4 === 0) {
        ticks.push({ position: pxPos, width: 6 });
      } else if (i % 2 === 0) {
        ticks.push({ position: pxPos, width: 4 });
      } else {
        ticks.push({ position: pxPos, width: 2 });
      }
    }
  } else {
    const mmTwips = TWIPS_PER_CM / 10;
    const totalMm = Math.ceil(pageHeightTwips / mmTwips);

    for (let i = 0; i <= totalMm; i++) {
      const twipsPos = i * mmTwips;
      if (twipsPos > pageHeightTwips) break;

      const pxPos = twipsToPixels(twipsPos) * zoom;

      if (i % 10 === 0) {
        const cm = i / 10;
        ticks.push({
          position: pxPos,
          width: 10,
          label: cm > 0 ? String(cm) : undefined,
        });
      } else if (i % 5 === 0) {
        ticks.push({ position: pxPos, width: 6 });
      } else {
        ticks.push({ position: pxPos, width: 3 });
      }
    }
  }

  return ticks;
}

export default VerticalRuler;

// packages/vue/src/components/ui/VerticalRuler.vue
<!--
  Mirrors packages/react/src/components/ui/VerticalRuler.tsx 1:1.
  20px wide, eighth-inch ticks (heights 10/6/4/2 from the right edge),
  same margin-marker styling.
-->
<template>
  <div
    ref="rulerRef"
    class="docx-vertical-ruler"
    :style="containerStyle"
    role="slider"
    aria-label="Vertical ruler"
    aria-orientation="vertical"
  >
    <!-- Tick marks -->
    <div class="docx-vertical-ruler__ticks">
      <template v-for="(tick, i) in ticks" :key="i">
        <div
          class="docx-vertical-ruler__tick-line"
          :style="{ top: tick.position + 'px', width: tick.width + 'px' }"
        />
        <div
          v-if="tick.label"
          class="docx-vertical-ruler__tick-label"
          :style="{ top: tick.position + 'px' }"
        >
          {{ tick.label }}
        </div>
      </template>
    </div>

    <!-- Top margin marker — left-pointing triangle -->
    <div
      v-if="editable"
      class="docx-vertical-ruler__marker"
      :style="markerStyle(topMarginPx)"
      @mousedown.prevent="startDrag('topMargin', $event)"
      @mouseenter="hovered = 'topMargin'"
      @mouseleave="hovered = null"
    >
      <div :style="triangleStyle('topMargin')" />
    </div>

    <!-- Bottom margin marker — left-pointing triangle -->
    <div
      v-if="editable"
      class="docx-vertical-ruler__marker"
      :style="markerStyle(pageHeightPx - bottomMarginPx)"
      @mousedown.prevent="startDrag('bottomMargin', $event)"
      @mouseenter="hovered = 'bottomMargin'"
      @mouseleave="hovered = null"
    >
      <div :style="triangleStyle('bottomMargin')" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onBeforeUnmount, type CSSProperties } from 'vue';
import type { SectionProperties } from '@sqren/docx-editor-core/types/document';
import { twipsToPixels, pixelsToTwips } from '@sqren/docx-editor-core/utils/units';

type MarkerType = 'topMargin' | 'bottomMargin';

const props = withDefaults(
  defineProps<{
    sectionProps?: SectionProperties | null;
    zoom?: number;
    editable?: boolean;
    unit?: 'inch' | 'cm';
  }>(),
  { zoom: 1, editable: true, unit: 'inch' }
);

const emit = defineEmits<{
  (e: 'top-margin-change', twips: number): void;
  (e: 'bottom-margin-change', twips: number): void;
}>();

const DEFAULT_PAGE_HEIGHT_TWIPS = 15840;
const DEFAULT_MARGIN_TWIPS = 1440;
const TWIPS_PER_INCH = 1440;
const TWIPS_PER_CM = 567;
const RULER_W = 20;

const rulerRef = ref<HTMLElement | null>(null);
const dragging = ref<MarkerType | null>(null);
const hovered = ref<MarkerType | null>(null);

// Same wrappers as HorizontalRuler — pin core's units helpers to the
// current zoom factor so subpixel positions match React exactly.
function tw2px(twips: number): number {
  return twipsToPixels(twips) * props.zoom;
}
function px2tw(px: number): number {
  return Math.round(pixelsToTwips(px / props.zoom));
}

const pageHeightTwips = computed(() => props.sectionProps?.pageHeight ?? DEFAULT_PAGE_HEIGHT_TWIPS);
const topMarginTwips = computed(() => props.sectionProps?.marginTop ?? DEFAULT_MARGIN_TWIPS);
const bottomMarginTwips = computed(() => props.sectionProps?.marginBottom ?? DEFAULT_MARGIN_TWIPS);

const pageHeightPx = computed(() => tw2px(pageHeightTwips.value));
const topMarginPx = computed(() => tw2px(topMarginTwips.value));
const bottomMarginPx = computed(() => tw2px(bottomMarginTwips.value));

const containerStyle = computed<CSSProperties>(() => ({
  position: 'relative',
  width: RULER_W + 'px',
  height: pageHeightPx.value + 'px',
  backgroundColor: 'transparent',
  overflow: 'visible',
  userSelect: 'none',
  cursor: dragging.value ? 'ns-resize' : 'default',
}));

// Mirror generateVerticalTicks() from React VerticalRuler.tsx.
const ticks = computed(() => {
  const out: { position: number; width: number; label?: string }[] = [];
  if (props.unit === 'inch') {
    const eighth = TWIPS_PER_INCH / 8;
    const total = Math.ceil(pageHeightTwips.value / eighth);
    for (let i = 0; i <= total; i++) {
      const tw = i * eighth;
      if (tw > pageHeightTwips.value) break;
      const px = tw2px(tw);
      if (i % 8 === 0) {
        out.push({ position: px, width: 10, label: i / 8 > 0 ? String(i / 8) : undefined });
      } else if (i % 4 === 0) {
        out.push({ position: px, width: 6 });
      } else if (i % 2 === 0) {
        out.push({ position: px, width: 4 });
      } else {
        out.push({ position: px, width: 2 });
      }
    }
  } else {
    const mm = TWIPS_PER_CM / 10;
    const total = Math.ceil(pageHeightTwips.value / mm);
    for (let i = 0; i <= total; i++) {
      const tw = i * mm;
      if (tw > pageHeightTwips.value) break;
      const px = tw2px(tw);
      if (i % 10 === 0) {
        out.push({ position: px, width: 10, label: i / 10 > 0 ? String(i / 10) : undefined });
      } else if (i % 5 === 0) {
        out.push({ position: px, width: 6 });
      } else {
        out.push({ position: px, width: 3 });
      }
    }
  }
  return out;
});

function markerStyle(top: number): CSSProperties {
  return {
    position: 'absolute',
    top: top - 5 + 'px',
    right: 0,
    width: RULER_W + 'px',
    height: '10px',
    cursor: props.editable ? 'ns-resize' : 'default',
    zIndex: dragging.value === null ? 1 : 10,
  };
}

// CSS triangle pointing left, mirrors React VerticalRuler.tsx
// triangleStyle: 5px transparent top/bottom + 8px right-border
// (which renders as a triangle pointing toward the page).
function triangleStyle(type: MarkerType): CSSProperties {
  const isActive = dragging.value === type;
  const isHovered = hovered.value === type;
  const color = isActive
    ? 'var(--doc-primary-hover)'
    : isHovered
      ? 'var(--doc-primary)'
      : 'var(--doc-primary)';
  return {
    position: 'absolute',
    top: '0px',
    right: '2px',
    width: '0',
    height: '0',
    borderTop: '5px solid transparent',
    borderBottom: '5px solid transparent',
    borderRight: `8px solid ${color}`,
    transition: 'border-right-color 0.1s',
  };
}

let dragStartY = 0;
let dragStartValue = 0;

function startDrag(type: MarkerType, event: MouseEvent) {
  if (!props.editable) return;
  dragging.value = type;
  dragStartY = event.clientY;
  dragStartValue = type === 'topMargin' ? topMarginTwips.value : bottomMarginTwips.value;
  document.addEventListener('mousemove', handleMove);
  document.addEventListener('mouseup', handleUp);
}

function handleMove(e: MouseEvent) {
  if (!dragging.value) return;
  const dy = e.clientY - dragStartY;
  const dTwips = px2tw(dragging.value === 'topMargin' ? dy : -dy);
  const max = pageHeightTwips.value -
    (dragging.value === 'topMargin' ? bottomMarginTwips.value : topMarginTwips.value) - 720;
  const value = Math.round(Math.max(0, Math.min(dragStartValue + dTwips, max)));
  if (dragging.value === 'topMargin') emit('top-margin-change', value);
  else emit('bottom-margin-change', value);
}

function handleUp() {
  dragging.value = null;
  document.removeEventListener('mousemove', handleMove);
  document.removeEventListener('mouseup', handleUp);
}

onBeforeUnmount(() => {
  document.removeEventListener('mousemove', handleMove);
  document.removeEventListener('mouseup', handleUp);
});
</script>

<style scoped>
.docx-vertical-ruler {
  display: block;
  flex-shrink: 0;
}
.docx-vertical-ruler__ticks {
  position: absolute;
  inset: 0;
  pointer-events: none;
}
.docx-vertical-ruler__tick-line {
  position: absolute;
  right: 0;
  height: 1px;
  background-color: var(--doc-text-subtle);
}
.docx-vertical-ruler__tick-label {
  position: absolute;
  left: 2px;
  transform: translateY(-50%);
  font-size: 9px;
  color: var(--doc-text-muted);
  font-family: sans-serif;
  white-space: nowrap;
}
.docx-vertical-ruler__marker {
  background: transparent;
}
</style>
