// packages/vue/src/components/ui/TableGridInline.vue
<!--
  Vue port of packages/react/src/components/ui/TableGridInline.tsx —
  inline grid picker for table dimensions (no button wrapper, used by
  menu-bar Insert > Table submenus). TableGridPicker.vue uses this
  pattern internally; this file matches the React file by name for
  consumers that import the inline version directly.
-->
<template>
  <div>
    <div
      class="docx-table-grid-inline__grid"
      :style="{ gridTemplateColumns: `repeat(${gridColumns}, 18px)` }"
      role="grid"
      aria-label="Table size selector"
      @mouseleave="hoverRows = 0; hoverCols = 0"
    >
      <div
        v-for="cell in cells"
        :key="`${cell.r}-${cell.c}`"
        class="docx-table-grid-inline__cell"
        :class="{ 'docx-table-grid-inline__cell--active': cell.r <= hoverRows && cell.c <= hoverCols }"
        role="gridcell"
        :aria-selected="cell.r <= hoverRows && cell.c <= hoverCols"
        @mouseenter="hoverRows = cell.r; hoverCols = cell.c"
        @click.prevent="handleClick"
      />
    </div>
    <div class="docx-table-grid-inline__label">
      {{ hoverRows > 0 && hoverCols > 0 ? `${hoverCols} × ${hoverRows}` : 'Select size' }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

const props = withDefaults(
  defineProps<{
    gridRows?: number;
    gridColumns?: number;
  }>(),
  { gridRows: 6, gridColumns: 6 }
);

const emit = defineEmits<{
  (e: 'insert', rows: number, cols: number): void;
}>();

const hoverRows = ref(0);
const hoverCols = ref(0);

const cells = computed(() => {
  const out: { r: number; c: number }[] = [];
  for (let r = 1; r <= props.gridRows; r++) {
    for (let c = 1; c <= props.gridColumns; c++) {
      out.push({ r, c });
    }
  }
  return out;
});

function handleClick() {
  if (hoverRows.value > 0 && hoverCols.value > 0) {
    emit('insert', hoverRows.value, hoverCols.value);
  }
}
</script>

<style scoped>
.docx-table-grid-inline__grid {
  display: grid;
  gap: 2px;
}
.docx-table-grid-inline__cell {
  width: 18px;
  height: 18px;
  background: var(--doc-surface);
  border: 1px solid var(--doc-border);
  border-radius: 2px;
  cursor: pointer;
  transition: background-color 0.1s, border-color 0.1s;
}
.docx-table-grid-inline__cell--active {
  background: var(--doc-primary);
  border-color: var(--doc-primary);
}
.docx-table-grid-inline__label {
  margin-top: 6px;
  font-size: 11px;
  font-weight: 500;
  color: var(--doc-text-muted);
  text-align: center;
}
</style>

// packages/react/src/components/ui/TableGridInline.tsx
/**
 * TableGridInline — a grid picker for table dimensions, rendered inline (no button/dropdown wrapper).
 * Used both standalone inside menu submenus and internally by TableGridPicker.
 */

import { useState, useCallback } from 'react';
import type { CSSProperties, ReactElement } from 'react';

interface TableGridInlineProps {
  onInsert: (rows: number, columns: number) => void;
  gridRows?: number;
  gridColumns?: number;
}

const CELL_SIZE = 18;
const CELL_GAP = 2;

const cellStyle: CSSProperties = {
  width: CELL_SIZE,
  height: CELL_SIZE,
  backgroundColor: 'var(--doc-surface)',
  border: '1px solid var(--doc-border)',
  borderRadius: 2,
  transition: 'background-color 0.1s, border-color 0.1s',
  cursor: 'pointer',
};

const cellSelectedStyle: CSSProperties = {
  ...cellStyle,
  backgroundColor: 'var(--doc-primary)',
  border: '1px solid var(--doc-primary)',
};

const labelStyle: CSSProperties = {
  marginTop: 6,
  fontSize: 11,
  fontWeight: 500,
  color: 'var(--doc-text)',
  textAlign: 'center',
};

export function TableGridInline({ onInsert, gridRows = 6, gridColumns = 6 }: TableGridInlineProps) {
  const [hoverRows, setHoverRows] = useState(0);
  const [hoverCols, setHoverCols] = useState(0);

  const handleCellClick = useCallback(() => {
    if (hoverRows > 0 && hoverCols > 0) {
      onInsert(hoverRows, hoverCols);
    }
  }, [hoverRows, hoverCols, onInsert]);

  const gridCells: ReactElement[] = [];
  for (let row = 1; row <= gridRows; row++) {
    for (let col = 1; col <= gridColumns; col++) {
      const isSelected = row <= hoverRows && col <= hoverCols;
      gridCells.push(
        <div
          key={`${row}-${col}`}
          style={isSelected ? cellSelectedStyle : cellStyle}
          onMouseEnter={() => {
            setHoverRows(row);
            setHoverCols(col);
          }}
          onClick={handleCellClick}
          role="gridcell"
          aria-selected={isSelected}
        />
      );
    }
  }

  const gridLabel = hoverRows > 0 && hoverCols > 0 ? `${hoverCols} × ${hoverRows}` : 'Select size';

  return (
    <div>
      <div
        style={{
          display: 'grid',
          gap: CELL_GAP,
          gridTemplateColumns: `repeat(${gridColumns}, ${CELL_SIZE}px)`,
        }}
        onMouseLeave={() => {
          setHoverRows(0);
          setHoverCols(0);
        }}
        role="grid"
        aria-label="Table size selector"
      >
        {gridCells}
      </div>
      <div style={labelStyle}>{gridLabel}</div>
    </div>
  );
}
